server:
  #端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码
    password: FVWKRSTCTGMKDXLE
    # 发送者邮箱地址
    username: shitoumao666@163.com
    # 端口 （不同邮箱端口号不同）
    port: 25

  #rabbitmq   配置
  rabbitmq:
    username: yeb
    password: yeb
    host: 192.168.1.30
    port: 5672